name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build and Test default scheme using any available Apple simulator
    runs-on: macos-latest
    strategy:
      matrix:
        xcode_version:
          - latest-stable

    steps:
      - uses: actions/checkout@v3
      - name: Show environments
        run: |
          swift --version
          xcodebuild -version
      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
      - name: Resolve dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: make resolve-dependencies
      - uses: actions/cache@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Test library
        run: make test-library
      - name: Build examples
        run: make build-examples